### ISSUE TITLE
How to remove the bar background color

### ISSUE THREAD

**Issue by awaluddinkasim** [AymanProjects/Molten_NavigationBar_Flutter#2]
When I have a long content inside a SafeArea widget, there's a little gap at the bottom behind the dome

**Comment by AymanProjects** [comment]
Hi @awaluddinkasim, please share a sample code, and a screenshot of the issue.

**Comment by awaluddinkasim** [comment]
Nevermind, I fixed the issue by setting the bottom parameter to false inside SafeArea widget

`SafeArea(
        bottom: false,
        child: ...
),`
